# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2014-12-22 12:27+0100\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=CHARSET\n"
"Content-Transfer-Encoding: 8bit\n"

#: ../usr/lib/ddm/ddm.py:46 ../usr/lib/ddm/main.py:26
#: ../debian/ddm/usr/lib/ddm/ddm.py:46 ../debian/ddm/usr/lib/ddm/main.py:26
#: ../usr/share/applications/ddm.desktop.in.h:1
#: ../debian/ddm/usr/share/applications/ddm.desktop.in.h:1
msgid "Device Driver Manager"
msgstr ""

#: ../usr/lib/ddm/ddm.py:47 ../debian/ddm/usr/lib/ddm/ddm.py:47
msgid "Save"
msgstr ""

#: ../usr/lib/ddm/ddm.py:48 ../debian/ddm/usr/lib/ddm/ddm.py:48
msgid "Help"
msgstr ""

#: ../usr/lib/ddm/ddm.py:49 ../debian/ddm/usr/lib/ddm/ddm.py:49
msgid "Quit"
msgstr ""

#: ../usr/lib/ddm/ddm.py:103 ../debian/ddm/usr/lib/ddm/ddm.py:103
msgid "No internet connection"
msgstr ""

#: ../usr/lib/ddm/ddm.py:104 ../debian/ddm/usr/lib/ddm/ddm.py:104
msgid ""
"You need an internet connection to install the additional software.\n"
"Please, connect to the internet and try again."
msgstr ""

#: ../usr/lib/ddm/ddm.py:154 ../debian/ddm/usr/lib/ddm/ddm.py:154
msgid "Install"
msgstr ""

#: ../usr/lib/ddm/ddm.py:154 ../debian/ddm/usr/lib/ddm/ddm.py:154
msgid "Device"
msgstr ""

#: ../usr/lib/ddm/ddm.py:189 ../debian/ddm/usr/lib/ddm/ddm.py:189
msgid "Hardware scan"
msgstr ""

#: ../usr/lib/ddm/ddm.py:193 ../debian/ddm/usr/lib/ddm/ddm.py:193
msgid "There are no available drivers for your hardware:"
msgstr ""

#: ../usr/lib/ddm/ddm.py:199 ../debian/ddm/usr/lib/ddm/ddm.py:199
msgid "DDM did not find any supported hardware."
msgstr ""

#: ../usr/lib/ddm/ddm.py:247 ../debian/ddm/usr/lib/ddm/ddm.py:247
msgid "Saved"
msgstr ""

#: ../usr/lib/ddm/ddm.py:248 ../debian/ddm/usr/lib/ddm/ddm.py:248
msgid "You will need to restart your system."
msgstr ""

#: ../usr/lib/ddm/ddm.py:426 ../debian/ddm/usr/lib/ddm/ddm.py:426
msgid "PAE capable system"
msgstr ""

#: ../usr/lib/ddm/ddm.py:512 ../debian/ddm/usr/lib/ddm/ddm.py:512
msgid ""
"There was an error during the installation.\n"
"Please, run 'sudo apt-get -f install' in a terminal.\n"
"Visit our forum for support: http://forums.solydxk.com"
msgstr ""

#: ../usr/lib/ddm/ddm.py:521 ../debian/ddm/usr/lib/ddm/ddm.py:521
msgid "The software has been successfully installed."
msgstr ""

#: ../usr/lib/ddm/main.py:27 ../debian/ddm/usr/lib/ddm/main.py:27
msgid ""
"Device Driver Manager cannot be started in a live environment\n"
"You can use the --force argument to start DDM in a live environment"
msgstr ""

#: ../usr/lib/ddm/main.py:77 ../debian/ddm/usr/lib/ddm/main.py:77
msgid "Unexpected error"
msgstr ""

#: ../usr/lib/ddm/main.py:78 ../debian/ddm/usr/lib/ddm/main.py:78
msgid ""
"Device Driver Manager has failed with the following unexpected error.\n"
"Please submit a bug report!"
msgstr ""
